[toolchain]
package_manager = "npm"

[programs.localnet]
trana = "GYhng7fbz51319ZwD1uBunBZs777C3KjmS52rYRcKfXn"

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx jest --runInBand"
