[toolchain]

[features]
resolution = true
seeds = true

[programs.devnet]
guard = "572t8Ctxx1nrHgxJZ1EHSNZTLcMH4oxV1R6g2pRAqba6"
demo_vault = "Cm2jPgn1ipUAFarS7DpF2Y1X1HofKZgDKLmH65DtCNrZ"

[programs.localnet]
guard = "572t8Ctxx1nrHgxJZ1EHSNZTLcMH4oxV1R6g2pRAqba6"
demo_vault = "Cm2jPgn1ipUAFarS7DpF2Y1X1HofKZgDKLmH65DtCNrZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"
