// Copyright 2025 Trana, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Trana Guard IDL — auto-generated by `anchor build`, committed to source.
 *
 * To refresh after program changes:
 *   anchor build && node scripts/sync-idl.js
 *
 * The TypeScript type `TranaGuard` is the full IDL-derived type used as
 * a generic parameter for `anchor.Program<TranaGuard>`, giving callers
 * typed access to every account, instruction, and error.
 */

import guardIdlJson from "../idl/trana_guard.json"

// IDL type — generated by `anchor build`, kept in sync via `node scripts/sync-idl.js`.
export type { TranaGuard } from "../types/trana_guard"

export const IDL = guardIdlJson as unknown as import("@coral-xyz/anchor").Idl
