// Copyright 2025 Trana, Inc.
// SPDX-License-Identifier: Apache-2.0

/**
 * Trana Authority IDL — auto-generated by `anchor build`, committed to source.
 *
 * To refresh after program changes:
 *   anchor build && node scripts/sync-idl.js
 */

import authorityIdlJson from "../idl/trana_authority.json"

// IDL type — generated by `anchor build`, kept in sync via `node scripts/sync-idl.js`.
export type { TranaAuthority } from "../types/trana_authority"

export const IDL = authorityIdlJson as unknown as import("@coral-xyz/anchor").Idl
